PS /home/mehrnoush> New-AzResourceGroup -Name 'Mehrnoush_DR' -Location 'East US' -Force                                                                                                                            
ResourceGroupName : Mehrnoush_DR
Location          : eastus
ProvisioningState : Succeeded
Tags              : 
ResourceId        : /subscriptions/e0b83536-7137-4a8e-96c5-2b997bd8c016/resourceGroups/Mehrnoush_DR


PS /home/mehrnoush> Register-AzresourceProvider -ProviderNamespace Microsoft.DBformySQL                                                                                      
ProviderNamespace : Microsoft.DBforMySQL
RegistrationState : Registering
ResourceTypes     : {operations, servers, flexibleServers, servers/recoverableServers…}
Locations         : {Australia Central, Australia Central 2, Australia East, Australia Southeast…}


PS /home/mehrnoush> get-AzResourceProvider -ProviderNamespace Microsoft.DBformySQL |ft

ProviderNamespace    RegistrationState ResourceTypes                                                 Locations
-----------------    ----------------- -------------                                                 ---------                                      
Microsoft.DBforMySQL Registered        {operations}                                                  {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {servers}                                                     {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {flexibleServers}                                             {Australia Central, Australia Southeast, Canad…
Microsoft.DBforMySQL Registered        {servers/recoverableServers}                                  {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {servers/virtualNetworkRules}                                 {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {locations/capabilities}                                      {Australia Central, Australia Southeast, Canad…
Microsoft.DBforMySQL Registered        {locations/checkNameAvailability}                             {Australia East, Australia Central, Australia …
Microsoft.DBforMySQL Registered        {checkNameAvailability}                                       {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {assessForMigration}                                          {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {getPrivateDnsZoneSuffix}                                     {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {locations/checkVirtualNetworkSubnetUsage}                    {Australia Central, Australia Southeast, Canad…
Microsoft.DBforMySQL Registered        {locations/listMigrations}                                    {Australia Central, Australia Southeast, Canad…
Microsoft.DBforMySQL Registered        {locations/updateMigration}                                   {Australia Central, Australia Southeast, Canad…
Microsoft.DBforMySQL Registered        {locations}                                                   {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {locations/operationResults}                                  {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {locations/azureAsyncOperation}                               {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {locations/administratorOperationResults}                     {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {locations/administratorAzureAsyncOperation}                  {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {locations/privateEndpointConnectionProxyOperationResults}    {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {locations/privateEndpointConnectionProxyAzureAsyncOperation} {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {locations/privateEndpointConnectionOperationResults}         {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {locations/privateEndpointConnectionAzureAsyncOperation}      {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {locations/performanceTiers}                                  {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {locations/securityAlertPoliciesAzureAsyncOperation}          {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {locations/securityAlertPoliciesOperationResults}             {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {locations/recommendedActionSessionsAzureAsyncOperation}      {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {locations/recommendedActionSessionsOperationResults}         {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {servers/topQueryStatistics}                                  {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {servers/queryTexts}                                          {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {servers/waitStatistics}                                      {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {servers/resetQueryPerformanceInsightData}                    {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {servers/advisors}                                            {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {servers/privateLinkResources}                                {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {servers/privateEndpointConnections}                          {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {servers/privateEndpointConnectionProxies}                    {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {servers/keys}                                                {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {locations/serverKeyAzureAsyncOperation}                      {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {locations/serverKeyOperationResults}                         {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {servers/start}                                               {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {servers/stop}                                                {Australia Central, Australia Central 2, Austr…
Microsoft.DBforMySQL Registered        {servers/upgrade}                                             {Australia Central, Australia Central 2, Austr…

PS /home/mehrnoush> 